install:
  - npm install
  - npm rebuild node-sass
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: $aws_access_key_id
  secret_access_key: $aws_secret_access_key
  bucket: haystackhq.com
  skip_cleanup: true
  acl: public_read
  local_dir: dist
  cache_control: "max-age=31536000"
addons:
  artifacts:
    debug: true
  s3_region: "us-west-2"
