install:
  - npm install
  - npm rebuild node-sass
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: $aws_access_key_id
  secret_access_key: $aws_secret_access_key
  bucket: "haystack-website-test"
  skip_cleanup: true
